### ISSUE TITLE
Error: The module was compiled against a different version of node.js

### ISSUE THREAD

**Issue by xeschylus** [vweevers/win-version-info#10]
Hello,
I am attempting to use this module in an Electron application but am getting the following error:

Uncaught Error: The module '(removed)\Launcher\node_modules\win-version-info\build\Release\VersionInfo.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

I have searched for and attempted a few methods to rebuild/recompile the package but am having no luck. I'm not terribly well versed in package management so this is probably a user issue more than project issue.  I would appreciate any help you might have.   

Thanks.

Node Version: 10.16.0
Windows 10

**Comment by vweevers** [comment]
See https://github.com/electron/electron-rebuild
