### ISSUE TITLE
Move to N-API with prebuildify

### ISSUE THREAD

**Issue by vweevers** [vweevers/win-version-info#17]
https://github.com/vweevers/win-version-info/pull/16#issuecomment-674486008

**Comment by chscott** [comment]
Has there been any progress on this effort? I maintain a project using win-version-info, and the existing module won't work after the Electron change to deprecate non-context-aware modules.

```
(node:9612) Electron: Loading non-context-aware native module in renderer: '\\?\C:\src\console\out\node_modules\win-version-info\build\Release\VersionInfo.node'. This is deprecated, see https://github.com/electron/electron/issues/18397.
```

I believe this issue will add the support needed for the module to work in recent versions of Electron.

**Comment by sagarsoni7** [comment]
@chscott - Did you find any workaround?

**Comment by chscott** [comment]
> @chscott - Did you find any workaround?

No, but I'm actually working on an Electron update to my app today that brings this issue back into the picture. I'll let you know if I find anything useful, but I think this module simply won't work until it is moved to N-API.

**Comment by chscott** [comment]
@sagarsoni7 As suspected, I cannot use win-version-info because it is not context-aware and thus won't work with recent versions of Electron. I had to end up removing it from my project and replacing it with a non-dependency approach.

**Before**

```
import VersionInfo from 'win-version-info'

let GetFileInfo: typeof VersionInfo | null = null
if (__WIN32__) {
  GetFileInfo = require('win-version-info')
}

  try {
    const info = GetFileInfo(path)
    const parts = info.FileVersion.split('.')
    if (parts.length === 0) {
      // Unknown version string
      return undefined
    }

    const buildNumber = parseSafeInt(parts[parts.length - 1])
    if (buildNumber === undefined) {
      // We can't parse the build number
      return undefined
    }

    return buildNumber
  } catch (e) {
    log.warn(`[${whoami}] Unable to read the build number for ${path}`, e)
    return undefined
  }
```

**After**

```
try {
    const result = await exec(
      `wmic datafile where "name='${path
        .split('\\')
        .join('\\\\')}'" get version`
    )
    const parts = result.split('\n')[1].split('.')
    if (parts.length === 0) {
      // Unknown version string
      return undefined
    }

    const buildNumber = parseSafeInt(parts[parts.length - 1])
    if (buildNumber === undefined) {
      // We can't parse the build number
      return undefined
    }

    return buildNumber
  } catch (e) {
    log.warn(`[${whoami}] Unable to read the build number for ${path}`, e)
    return undefined
  }
```

**Comment by vweevers** [comment]
[5.0.0](https://github.com/vweevers/win-version-info/releases/tag/v5.0.0) / [5.0.1](https://github.com/vweevers/win-version-info/releases/tag/v5.0.1).
