### ISSUE TITLE
Request: Support for all versions of Node 14

### ISSUE THREAD

**Issue by ZhaeSei** [vweevers/win-version-info#19]
Supporting Nodejs 14.2.0 was done in this pr https://github.com/vweevers/win-version-info/pull/16. Could support be added for all versions of Node 14?

**Comment by vweevers** [comment]
That PR added a prebuild suitable for any Node.js 14.x version (because the ABI doesn't change within a major release line). The only reason it uses 14.2 is to circumvent an Appveyor issue.
