### ISSUE TITLE
It would be nice if you could add `support Node.js only` to `READMEmd` for more detail

### ISSUE THREAD

**Issue by loclv** [vweevers/win-version-info#20]
Thank you for awesome package! :100: 

It would be nice if you could add `support Node.js only` to `READMEmd` for more detail.

I realized that one of package's dependency is [node.js fs](https://nodejs.org/api/fs.html), so i can't use it on browser. :cry:

**Comment by vweevers** [comment]
The first line of the README says "Windows-only _native addon_". Doesn't that cover it?

PS. The node core `fs` module isn't used here. The native addon calls a Win32 API (GetFileVersionInfoW) which in turn reads the file.

**Comment by loclv** [comment]
@vweevers 
Thank you for your explanation!
